### ISSUE TITLE
Noto Sans for English Toolbar titles (Not Noto Sans Tibetan)

### ISSUE THREAD

**Issue by subsystem7** [BuddhistDigitalResourceCenter/BDRC-Lib-App#1]
This will work better than Noto for English, centering properly.

**Comment by eroux** [comment]
can you provide a small before/after example please? I'm not sure what English Toolbar titles are, nor why this change pops up

**Comment by eroux** [comment]
(pinging @tfrere)

**Comment by subsystem7** [comment]
Notice the Tibetan title looks good, fits well:
![image](https://cloud.githubusercontent.com/assets/1638461/26793981/f59a3600-49ed-11e7-818a-98f4cd44bee6.png)

Notice the English title is not right.  This is because it is still honoring the Noto Sans Tibetan type.  At first I was thinking Roboto replacement, now I think just knowing when it is english, and changing it to pure Noto Sans is likely the solution. 
![image](https://cloud.githubusercontent.com/assets/1638461/26794009/0cb96a7c-49ee-11e7-8902-7536c8b95345.png)

**Comment by eroux** [comment]
I concur that when the title is in Latin script, the font should be `NotoSans` (not `NotoSans-Tibetan`)... so there's no more question on our side?
