### ISSUE TITLE
Shareable link to the book

### ISSUE THREAD

**Issue by Drongbulobsang** [BuddhistDigitalResourceCenter/BDRC-Lib-App#127]
![image](https://github.com/buda-base/BDRC-Lib-App/assets/42564256/661ea8b5-e287-4f9c-8711-1ba4b1522d17)

put a shareable link to the book maybe better.

**Comment by subsystem7** [comment]
This is what I see. It is a standard share box that allows the copy of a link:

![Image](https://github.com/buda-base/BDRC-Lib-App/assets/1638461/b36f21e6-42b5-4234-a108-bfcc2977de00)
