### ISSUE TITLE
Detail View: Replace RID header with title

### ISSUE THREAD

**Issue by subsystem7** [BuddhistDigitalResourceCenter/BDRC-Lib-App#14]
NT: Replace the RID in header by title, for non-librarian terrestrials 

![image](https://user-images.githubusercontent.com/1638461/27334908-d10811de-5598-11e7-9f03-e2418d07bd87.png)

**Comment by eroux** [comment]
I'm fine with that, the RID should still appear somewhere though, it can be more discrete

**Comment by subsystem7** [comment]
include RID with publication information
