### ISSUE TITLE
Dirk: App icon design is too square

### ISSUE THREAD

**Issue by subsystem7** [BuddhistDigitalResourceCenter/BDRC-Lib-App#16]
Small thing: App icon design is too square -- all other icons have rounded corners, so it looks off

**Comment by eroux** [comment]
Just in case: there's an alternative version of the logo, that scales better for small sizes [here](https://drive.google.com/open?id=0ByjQj1Jk5giJRXg2WnpXUmI1RWs), I don't know when it will be reviewed though (it may not be the final version)

**Comment by subsystem7** [comment]
Rounded the corners for the android icon
