### ISSUE TITLE
Identifier and fields are all disorder.

### ISSUE THREAD

**Issue by subsystem7** [BuddhistDigitalResourceCenter/BDRC-Lib-App#21]
Karma/Librarians: Identifier and fields are all disorder. See the screenshot as example.

![image](https://user-images.githubusercontent.com/1638461/27336363-4e866bca-559d-11e7-9fe7-6077f0543186.png)

**Comment by subsystem7** [comment]
@ngawangtrinley When you can, I need a screenshot with order of meta-data

**Comment by ngawangtrinley** [comment]
Here's the bug with W1PD76384

![image](https://user-images.githubusercontent.com/17675331/27400284-348769c6-56f2-11e7-9545-95fdbd87152c.png)

**Comment by subsystem7** [comment]
Got it.  It was just in the localization file.

![image](https://user-images.githubusercontent.com/1638461/27403172-7c8b52d8-5697-11e7-9368-2a5800279926.png)
