### ISSUE TITLE
If the full title exists in BDRC website/App

### ISSUE THREAD

**Issue by subsystem7** [BuddhistDigitalResourceCenter/BDRC-Lib-App#25]
Karma/Librarians: The good chance is the text is available in BDRC.

**Comment by ngawangtrinley** [comment]
In other words: "The status doesn't add any information in release 1, if a text is not in the database it's needed. If it's there we already have it." It makes sense. The status will becomes useful once: 1) it gets updated by the staff at each stage of processing, 2) the existing images are audited and we know what needs to be re-scanned.
