### ISSUE TITLE
Open images on page 3

### ISSUE THREAD

**Issue by ngawangtrinley** [BuddhistDigitalResourceCenter/BDRC-Lib-App#26]
Open a book on cover page, the 2 BDRC pages will still be there but users won't have to wait for them to load to get to the the cover page. It can make a big difference with a slow connection.

**Comment by subsystem7** [comment]
Consider implementing server side meta-data that indicates the starting slide page.

**Comment by eroux** [comment]
No need for that, it's always page 3, for all volumes

**Comment by subsystem7** [comment]
ok!

**Comment by subsystem7** [comment]
Done!
