### ISSUE TITLE
Customer service wechat in info

### ISSUE THREAD

**Issue by ngawangtrinley** [BuddhistDigitalResourceCenter/BDRC-Lib-App#28]
Add a QR code or link to a customer service account in info. The account can be followed by Dondrup during the day in Asia, and by Emma during the American day

**Comment by subsystem7** [comment]
Add a "WeChat" image to info panel. NT/Jeff will get Asa the image.

**Comment by subsystem7** [comment]
@ngawangtrinley I really need this image before noon Eastern US Time if possible.
