### ISSUE TITLE
Work Index Files Contain Publisher Names

### ISSUE THREAD

**Issue by subsystem7** [BuddhistDigitalResourceCenter/BDRC-Lib-App#35]
NT discovered that the search results contained publisher names as well as work titles and alternative work titles (or outline titles or author names). Looking at the index file, it appeared that all of these results were connected to values containing the work id twice... like this:

```
  "གསང་ཆེན་བསྟན་པའི་ཆུ་འགོ་རྒྱལ་བ་ཀཿ་ཐོག་པའི་ལོ་རྒྱུས་མདོར་བསྡུས་བརྗོད་པ་འཆི་མེད་ལྷའི་རྔ་སྒྲ་ངོ་མཚར་རྣ་བའི་དགའ་སྟོན": [
    "W20396-W20396"
  ]
```
(NOTE: I'm not sure whether this example is a publisher name or alternative title, it is just for illustration)

The result was that there was no detail file for any of the alternate titles (W20396-W20396.json did not exist, but W20396.json did, of course), or for publisher names. I added code that just used the first ID, which took care of the missing data problem.  However, it still did not look good to @ngawangtrinley to have publisher names with icons for works. Given that we could not figure out how to differentiate, NT determined it was best to drop all of the alternative titles and publisher names (anything with a dash in the RID).  So that is what the code does.

**Comment by eroux** [comment]
should be fixed with the new index given on Skype
