### ISSUE TITLE
App crashes after a couple of queries

### ISSUE THREAD

**Issue by ngawangtrinley** [BuddhistDigitalResourceCenter/BDRC-Lib-App#38]
## Query A: "བདེ་ལེགས་"
![1](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19244165_10154709316672467_1890035487_n.png?oh=740bdf0c156c6310ab21bc9063cf5edf&oe=59535041)

## Query A results:
![2](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19251136_10154709316647467_432252814_n.png?oh=fb4c938d2a830fc309de029cb76d913b&oe=5953066C)

## Query B: "དོན་གྲུབ་རྒྱལ་"
![3](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19512011_10154709316637467_1129926997_n.png?oh=3d078915045f3d890a6996a38842061c&oe=59532974)

## Repeat of query A: 
![4](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19512398_10154709316582467_683267477_n.png?oh=feaa68f4d600d5073595008d45528573&oe=59533E15)

## Repeat of query A after restarting my phone:
![5](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19553335_10154709316587467_1502724235_n.png?oh=53b4f4fd4c97f0706e212dcb80c2d9a3&oe=59543802)

## Query C "དོན་གྲུབ་" before all results of previous query could be displayed:
![6](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19489459_10154709316537467_1216070865_n.png?oh=87785fb201aadca6da9e5274cbd7c5d0&oe=595348BF)

## Query A again:
![7](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19206587_10154709316527467_1912339162_n.png?oh=6a07732eaf26d1559b80dd1c9f58c126&oe=5953687B)

## And query C after restarting:
![8](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19489404_10154709316492467_405002655_n.png?oh=b339d1ea1437f9aaf3c0a149e2cc8a2c&oe=5954356C)

## Quickly followed by query D "ཨེ་མ་ཧོ":
![9](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19512007_10154709316482467_279564145_n.png?oh=fcbda360a1312232e172ef3587b2998d&oe=59542ECA)

**Comment by subsystem7** [comment]
Hey NT! Yeah, this sounds bad. I never experienced this on my android phone. Are other people reporting this issue? Does it happen on iOS?

**Comment by ngawangtrinley** [comment]
I tested it on two OPPO phones, didn't test it on iOS. I'm suspecting that the feedback about clearing the cache was the same issue.

**Comment by subsystem7** [comment]
ok... I think I have made this happen on iOS also.. this is actually good news. Working on it. The error I get is unfortunately not clear. "SyntaxError: Unexpected EOF" so... I am continuing to look. Can you test whether there are other combinations of searches that do the same thing?

**Comment by ngawangtrinley** [comment]
Are you not on holiday? :D

**Comment by subsystem7** [comment]
It appears that searching for དོན་ག causes an error.  I am not sure why, but there is no need for more than one search to make this happen.  Yes... I am on holiday... but this seems like a show stopper, no?

**Comment by subsystem7** [comment]
Also, I can make it happen in the iOS emulator.  Unfortunately, I cannot make it happen in the browser version... which means it is related to the database, and means that debugging is going to be a bit more of a problem...

**Comment by subsystem7** [comment]
It is possible that this is the problem:
https://github.com/litehelpers/Cordova-sqlite-storage/issues/147

I am working on confirming this, and working around it.

**Comment by ngawangtrinley** [comment]
I'd say don't worry about it for now. It's definitely good enough for the training. It's really something about this "དོན་ག" word combination. On my phone, emptying the search field then closing and re-opening the app makes it come back to normal. 

It's funny because "དོན་གྲུབ་" or Dhondrup means "The one that makes things happen" and it's the name of my Tibetan colleague here who found the bug when looking for the famous author Dhondrup Gyal.

**Comment by subsystem7** [comment]
That is actually very funny... There are definitely a whole host of other searches that would have had the same effect. See #41
