### ISSUE TITLE
Emptying the app cache fixes it ... 1 time.

### ISSUE THREAD

**Issue by ngawangtrinley** [BuddhistDigitalResourceCenter/BDRC-Lib-App#39]
## App is frozen as described in #38:
![1](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19512008_10154709316747467_208594410_n.png?oh=209554a21f50be60c35c1f69d42b5061&oe=59532469)

## App cache is emptied:
I'm pretty sure the data comes from images loaded for reading
![2](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19489534_10154709316827467_2001879621_n.png?oh=861db0d90755275bd7854a10d658a7b5&oe=59535612)

## Query 1 and 2 work fine:
![4](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19512011_10154709316637467_1129926997_n.png?oh=3d078915045f3d890a6996a38842061c&oe=59532974)

## Query 3 crashes the app: 
![5](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19512398_10154709316582467_683267477_n.png?oh=feaa68f4d600d5073595008d45528573&oe=59533E15)

## Tried to clear the cache again but it's empty and doesn't make a difference: 
![3](https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/19489510_10154709316677467_254629039_n.png?oh=31ed323b97023daea692430cb0de77af&oe=59530D5E)

**Comment by subsystem7** [comment]
I am closing this, since it is a workaround/more data about #38 - which I believe has been resolved, but can also be further discussed under #41
