### ISSUE TITLE
U+2028 (LINE SEPARATOR) in index files appears to cause a fatal database error on resolution of a query

### ISSUE THREAD

**Issue by subsystem7** [BuddhistDigitalResourceCenter/BDRC-Lib-App#41]
This issue is likely related to this issue:

https://github.com/litehelpers/Cordova-sqlite-storage/issues/147

It appears that whenever a query returns results that contain one of the many indices where the key has the character combination '\n' -- a crash happens.  Here is an example.

"གྲགས་པ་རྒྱལ\nམཚན། གསུང་འབུམ":["W3GSP297"]

The temporary fix is to remove all of these from the index files.

**Comment by xristy** [comment]
If '\n' is a newline char it should be stripped out of names and titles. They are not needed and may cause problems elsewhere.

**Comment by ngawangtrinley** [comment]
This didn't solve the problem with "དོན་ག" and "དོན་གྲུབ་" though...

**Comment by subsystem7** [comment]
NT: did the app reimport when you launched the new version? You may need to uninstall it fully from your phone and try again. It tested fine on my iPhone. :(

**Comment by subsystem7** [comment]
I have now tested this on my android phone (S5) from the Play Store install, and the problem is no longer there with the latest release (last week).  Can you confirm, @ngawangtrinley ?

**Comment by subsystem7** [comment]
Just FYI: Here are the entries in the indexes that containe the unicode line separator:

[Log] possible bad data - found LINE SEPARATOR U+2028
[Log] རྗེ་བཙུན་བླ་མ་དམ་པ་མཁས་ཤིང་གྲུབ་པའི་དབང་ཕྱུག་བྲག་དཀར་རྡོ་རྗེ་འཆང་བློ་བཟང་དཔལ་ལྡན་བསྟན་འཛིན་སྙན་གྲགས་དཔལ་བཟང་པོའི་གསུང་འབུམ་གླེགས་བམ་ཕ་པའི་དཀར་ཆག
  O1PD84604-O1PD846041PD84851

[Log] possible bad data - found LINE SEPARATOR U+2028
[Log] དཔལ་རྡོ་རྗེ་འཇིགས་བྱེད་དཔའ་བོ་གཅིག་པའི་བསྐྱེད་རིམ་དངོས་གྲུབ་བདུད་རྩིའི་བུམ་བཟང།   O1PD84604-O1PD846041PD84867

[Log] possible bad data - found LINE SEPARATOR U+2028
[Log] དཔལ་རྡོ་རྗེ་འཇིགས་བྱེད་དཔའ་བོ་གཅིག་པའི་རིམ་གཉིས་ཀྱི་ཁྲིད་དངོས་གྲུབ་བདུད་རྩིའི་བུམ་བཟང་ལས་རིམ་པ་གཉིས་པའི་ཁྲིད།  O1PD84604-O1PD846041PD84869

[Log] possible bad data - found LINE SEPARATOR U+2028
[Log] ཐམས་ཅད་མཁྱེན་གཟིགས་རྗེ་བཙུན་བླ་མ་བློ་བཟང་དཔལ་ལྡན་བསྟན་འཛིན་སྙན་གྲགས་དཔལ་བཟང་པོའི་རྣམ་ཐར་ངོ་མཚར་སྐལ་བཟང་རྣ་བའི་བདུད་རྩིའི་ཁ་སྐོང་ཡིད་ཀྱི་གདུང་སེལ།  O1PD84604-O1PD846041PD84910

[Log] possible bad data - found LINE SEPARATOR U+2028
[Log] ངེས་པར་དོན་གྱི་རྡོ་རྗེ་འཆང་ཐམས་ཅད་མཁྱེན་གཟིགས་རྗེ་བཙུན་བླ་མ་བློ་བཟང་དཔལ་ལྡན་བསྟན་འཛིན་སྙན་གྲགས་དཔལ་བཟང་པོའི་རྣམ་ཐར་ངོ་མཚར་སྐལ་བཟང་རྣ་བའི་བདུད་རྩི།  O1PD84604-O1PD846041PD84907

**Comment by subsystem7** [comment]
I added code that removes U+2028 and U+2029 if they appear in the key.
