### ISSUE TITLE
label changes

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/BDRC-Lib-App#43]
As seen in the Skype discussion, @karmagongde requested to change the labels in the following way:

- [x] བརྩམས་ཆོས་ངོ་རྟགས into མི་སྣའི་ཨང་རྟགས
- [x] མཛད་པ་པོ into བརྩམས་ཆོས་ཁག

@ngawangtrinley can you please confirm?

**Comment by karmagongde** [comment]
I am not suggesting change all the བརྩམས་ཆོས་ངོ་རྟགས། into མི་སྣའི་ཨང་རྟགས། In BDRC Lib App, there are བརྩམས་ཆོས་ངོ་རྟགས། in two places, one in catalog info to indicate work number and other at Person record info.
This labeling issue is in Person record information not in catalog information.

For work number  བརྩམས་ཆོས་ངོ་རྟགས། into བརྩམས་ཆོས་ཨང་རྟགས།
For Person record  བརྩམས་ཆོས་ངོ་རྟགས། into མི་སྣའི་ཨང་རྟགས།

On the page of person record there is མཛད་པ་པོ། Under མཛད་པ་པོ། listed all the works of author, Therefore 
མཛད་པ་པོ།  into བརྩམས་ཆོས་ཁག

By the way, there is no naro on  བརྩམས་

![img_0154 1](https://user-images.githubusercontent.com/19337852/28120930-89d27056-66e7-11e7-8ce9-4e3b4bdea1e7.PNG)

**Comment by subsystem7** [comment]
in the localizations file, མཛད་པ་པོ  looks like:
```
CreatorOf:'མཛད་པ་པོ།',	
```
I can't find བརྩོམས་ཆོས་ངོ་རྟགས -- what does it mean @ngawangtrinley ?

**Comment by eroux** [comment]
བརྩོམས་ཆོས་ངོ་རྟགས a mispelling on my part, as indicated by @karmagongde, the correct spelling is བརྩམས་ཆོས་ཁག, I've fixed the initial comment

**Comment by subsystem7** [comment]
ok... so I am getting that there are some nuances to this labeling request. The RID label is different in the person detail than in the work detail.  I will need very specific and clear instruction with english translation. At the moment, RID is used for work, text, and person:
```
RID:'བརྩམས་ཆོས་ངོ་རྟགས།',
```

What I think may need to be done is to create PersonRID, WorkRID, TextRID, something like this:

```
PersonRID:'མི་སྣའི་ཨང་རྟགས།',
WorkRID:'བརྩམས་ཆོས་ཨང་རྟགས།',
TextRID:'བརྩམས་ཆོས་ཨང་རྟགས།',
```

and remove "RID"

The other change is to change the translation for creatorOf, which is the label on the person detail for authored works. The old is མཛད་པ་པོ, and the new would be:

```
CreatorOf:'མཛད་པ་པོ།',
```

Please advise if I have this right.

**Comment by karmagongde** [comment]
I have discussed with librarians and we all agreed of following translation.
PersonRID: མི་སྣའི་ཨང་རྟགས།
WorkRID: བརྩམས་ཆོས་ཨང་རྟགས།
TextRID are of outline's RID therefore, ས་བཅད་ཨང་རྟགས། 
CreatorOf: བརྩམས་ཆོས།

**Comment by jeffwallman** [comment]
@ngawangtrinley should vet all the translations.  @karmagongde please confirm @subsystem7's request about the CreatorOf label.

**Comment by karmagongde** [comment]
In my previous comment, I already listed translation of CreatorOf label. 
CreatorOf: བརྩམས་ཆོས།

**Comment by subsystem7** [comment]
Looking for final approval. Here are some screenshots of the new labels in action.

# WORK
![image](https://user-images.githubusercontent.com/1638461/28130080-bef0d68a-6703-11e7-8ae6-28f68c6ce4c6.png)

# PERSON
![image](https://user-images.githubusercontent.com/1638461/28130103-cf0d4b02-6703-11e7-8bc6-0882298f573a.png)

# OUTLINE
![image](https://user-images.githubusercontent.com/1638461/28130135-eabb342c-6703-11e7-86b3-357ed13e6979.png)

**Comment by karmagongde** [comment]
Work and Person labels are wonderful.
In outline it need to switch མཚན་བྱང་། and ས་བཅད། labels. The title of the book is གསུང་འབུམ། མཁྱེན་བརྩེའི་དབང་པོ། and outline Text is མཁྱེན་བརྩེའི་བྱང་ཆུབ་ལམ་རིམ་ཉམས་སུ་ལེན་ཚུལ་གྱི་ཕྱག་བཞེས་སྙིང་པོར་དྲིལ་བ།

**Comment by subsystem7** [comment]
@karmagongde @ngawangtrinley  - The following labels are used for outlines (in the order that they appear).

```
Title:'མཚན་བྱང་།',
OutlineRID:'ས་བཅད་ཨང་རྟགས།',
IsOutlineOf:'ས་བཅད།',	
```

__Title__ is the name of the text, and is used in other places throughout the system... so perhaps there is a better name for that on the outline page.

__Is Outline Of__ refers to the work that the outline is of. So in English, these labels make sense. 

please advise.

**Comment by karmagongde** [comment]
The skype and Github#43 received yesterday 6:20pm. I was out of office and could not able to reply. Sorry for that.
Generally Title means མཚན་བྱང་། I don't know anything what terms were used in field locations in App.
The screenshot of the Outline: གསུང་འབུམ། མཁྱེན་བརྩེའི་དབང་པོ། is main title; བྱང་ཆུབ་ལམ་རིམ་ཉམས་སུ་ལེན་ཚུལ་གྱི་ཕྱག་བཞེས་སྙིང་པོར་དྲིལ་བ། is outlined text.
In technical term, is there different between OutLine and IsOutLineOf? 
OutLine is ས་བཅད།

**Comment by xristy** [comment]
"Outline" (ས་བཅད) would be the heading for the actual outline.

"Is Outline Of" would be the heading for the Work RID that is being outlined

**Comment by karmagongde** [comment]
Thank you Chris, I also thought so. I looked in DLMS for a example.

**Comment by ngawangtrinley** [comment]
Hi everyone, sorry for not answering yesterday, I was traveling. @karmagongde my understanding was that the Outlines are a list of the texts in a volume, in which case དཀར་ཆག is more adapted. ས་བཅད། is more the content of a text.

**Comment by karmagongde** [comment]
Yes, དཀར་ཆག could be single work number or table of contents. ས་བཅད། is more like a detailed contents of a text.

**Comment by subsystem7** [comment]
ok, so is the outcome this?

```
Title:'ས་བཅད།',
OutlineRID:'ས་བཅད་ཨང་རྟགས།',
IsOutlineOf:'ཁུངས།',	
```

Thanks,
Asa

**Comment by xristy** [comment]
OutlineRID and IsOutlineOf are fine.

The Title should be reverted to:

Title: 'མཚན་བྱང་།'
