### ISSUE TITLE
swapped labels

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/BDRC-Lib-App#44]
`publisherName` should be `པར་གནས་` and `publisherDate` should be `པར་དུས་`, they are swapped now

**Comment by eroux** [comment]
@subsystem7 do you want me to swap the data between the two? I can do that so that you don't have to update the app

**Comment by subsystem7** [comment]
This is what I have in the localizations file at the moment:
```
PublisherName:'པར་མཁན།',
PublisherDate:'པར་གནས།',
PublisherLocation:'པར་དུས།',
```
To me it looks like you are saying that publisherName should have the publisherDate label, and that the publisherDate should have the publisherLocation value.  Is this correct?   If so, what should publisherLocation be?

In the application, I am displaying these elements in this order:
```
<StringSection title={this.props.strings.PublisherName} val={this.props.work.publisherName} /> 
<StringSection title={this.props.strings.PublisherLocation} val={this.props.work.publisherLocation} />
<StringSection title={this.props.strings.PublisherDate} val={this.props.work.publisherDate} />
```

Can you confirm? I sent the translations above to @ngawangtrinley to make sure, also.

**Comment by xristy** [comment]
I can confirm that PublisherDate and PublisherLocation are swapped. They should be:

PublisherDate: 'པར་དུས།' ,
PublisherLocation: 'པར་གནས།' ,

**Comment by subsystem7** [comment]
Changes made to LocalizedStrings.js
