### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by subsystem7** [BuddhistDigitalResourceCenter/BDRC-Lib-App#5]
Images in legacy image groups that required normalization are causing an exception in the image service and not displaying in the App.  Example: 

https://www.tbrc.org/browser/ImageService?work=W22084&igroup=I0981&image=1&first=1&last=530&fetchimg=yes

The image normalization code was removed from the app when the ImageService was updated to handle the normalization.

**Comment by xristy** [comment]
This is now fixed in the app server. Imagegroup names are now properly "normalized" according to legacy conventions

**Comment by subsystem7** [comment]
Thank you, Chris!!!
