### ISSUE TITLE
Single Creator name in Work View

### ISSUE THREAD

**Issue by ngawangtrinley** [BuddhistDigitalResourceCenter/BDRC-Lib-App#50]
Asa: Use the first author in the list.

![screenshot_2017-11-21-01-42-20-32](https://user-images.githubusercontent.com/17675331/33033539-a29ac52c-ce5f-11e7-84ff-56d9bd7bc0a5.png)
As shown in the above example, variants of an author's names are displayed in a work view (W1KG25095), and make users strain their thumbs scrolling down the list.

This name:
<work:creator person="P270">o rgyan 'jigs med chos kyi dbang po</work:creator>
should be displayed in a Work View.

The variants can appear in the Person View.
{"creatorOf":["W8LS19616","W8LS19323","W2CZ5981","W30038","W1KG24057","W1KG25095","W4PD913","W5741","W8LS17113","W00KG04062","W5743","W8LS24641","W8LS20832","W8LS19604","W21707","W8LS19422","W3CN9771","W5832","W24829","W1PD107142","W1KG21887","W1KG24014","W1KG2820","W8LS19972","W22270","W1KG3552","W21999","W1KG3818","W8LS16587","W3CN5420","W8LS16483","W1KG23850","W2CZ6659","W1KG12208","W1KG13014","W1KG3401","W3CN5444","W3PD441","W8LS19437","W8LS17020","W23370","W1PD45158","W4CZ299952","W21857","W8LS18308","W3CN4690","W1KG1578"],"name":["རྫོགས་ཆེན་མཁན་རབས ༠༥","ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ།","ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་དབང་།","རྫ་དཔལ་སྤྲུལ་ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ།","རྫོགས་ཆེན་མཁན་རབས ༠༥ ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ།","ཁྱི་རྒན་དཔལ་དགེ"]}

**Comment by eroux** [comment]
Hmm, so I guess only the first of the names should be displayed? I should make sure it's the "main" one, but I'm pretty sure it already is...

**Comment by jeffwallman** [comment]
Look at the website for a view of the creator information, as it appears in the work view.  You should select name variant #1 in the person record, for display on the work record.

**Comment by subsystem7** [comment]
![image](https://user-images.githubusercontent.com/1638461/33452457-49d02864-d5e0-11e7-9f04-44b659fb9fdb.png)
