### ISSUE TITLE
Share and Share PDF are confusing

### ISSUE THREAD

**Issue by ngawangtrinley** [BuddhistDigitalResourceCenter/BDRC-Lib-App#58]
I've observed a couple of users downloading and using the app for the first time, and they said that they find the term "Share" for a link to the website rather confusing. When they got to the link with the PDF, they said: "Oh, this is sharing right here. I can send this link and it sends the text!"

A suggestion was to rename the "Share" button to "Website", or "Online Library"...

**Comment by subsystem7** [comment]
perhaps "VIEW ONLINE"

**Comment by subsystem7** [comment]
Also, maybe we should just make it open a web browser. Could even be "Web Link" -- that way, a browser opens, and people can simply share from the browser. This would be my vote.
