### ISSUE TITLE
Access and Restriction message confusing

### ISSUE THREAD

**Issue by ngawangtrinley** [BuddhistDigitalResourceCenter/BDRC-Lib-App#59]
To do:
- [ ] change the message
- [ ] @eroux check the data for similar bugs

Users found it quite confusing that works like W1PD137818 could be viewed (partly they discovered), but was labeled "open access" in the metadata and "restricted" when trying to download. 

They also suggested the message could be made more human by writing something like "PDF can't be downloaded because it's copyrighted." rather than: "Error 207: ..."

![ff](https://user-images.githubusercontent.com/17675331/33610426-7a259fba-da06-11e7-9116-ec070883ff0b.png)

![f](https://user-images.githubusercontent.com/17675331/33610917-b27338e0-da07-11e7-92e5-ef67e299db6d.png)

**Comment by subsystem7** [comment]
This looks like a data problem. 

from the file:
W1PD137818.json

```
{"access":"open","license":"copyrighted","volumeMap":[{"id":"I4PD4215","total":378,"num":1}],"publisherDate":"2010","publisherName":"མི་རིགས་དཔེ་སྐྲུན་ཁང་།","hasCreator":["P2PD20575"],"title":["བོད་བཙན་པོའི་རྒྱལ་རབས་ཀྱི་ཆབ་སྲིད་ལམ་ལུགས་ཞིབ་འཇུག——བོད་ཀྱི་བརྡ་རྙིང་ཡིག་ཆ་ཁག་དཀྱུས་སུ་བཟུང་ནས་དཔྱད་པ།","བོད་བཙན་པོའི་རྒྱལ་རབས་ཀྱི་ཆབ་སྲིད་ལམ་ལུགས་ཞིབ་འཇུག"],"publisherLocation":"པེ་ཅིན།"}
```

**Comment by eroux** [comment]
license is about copyright, access is about restriction, data is meant to
be this way. The work is not restricted per second, so it's access is open,
but it's under copyright, so we only provide it under fair use.

**Comment by ngawangtrinley** [comment]
This actually looks like a bug in the data. The access [on the website](https://www.tbrc.org/?locale=en#!rid=W1PD137818) is Fair Use.

**Comment by eroux** [comment]
the data gets changed in the migration machinery, on purpose, so no, it is not a bug in the data

**Comment by jeffwallman** [comment]
Elie.  There is a misunderstanding.  

The work in question is restricted by copyright right.  In our case, this means, and this is what the metadata is saying, is that the access is restricted to fairUse.  There are no additional restrictions placed on the material.  Saying the license is copyright and access is fairUse is the way our metadata is defined.  Saying the license is copyright and the access is openAccess is not the way our metadata is defined.

So the issue is that the JSON files are incorrectly interpreting how the metadata is defined.

Does this make sense?

I believe that the App should be passing license and access restrictions to the app and these need also to be reflected on the link page.

**Comment by eroux** [comment]
I perfectly understand the current values of license and access yes, and you describe them well. I thought it would be better to make the change I made for some reasons I can explain (and that I tried to explain several times, but I guess that got lost in some email or some doc nobody reads). Shall I give another shot at my explanation or revert the change?

**Comment by eroux** [comment]
I'll make a spreadsheet in the next few days describing some cases, how they're currently encoded, the issues I find with the current encoding and a proposal for a new encoding (that will be used for the migrated data, not in the current system), that's probably the best solution. In the meantime, Asa, can you describe the logic you're using for error messages? I'll build the data accordingly.

**Comment by jeffwallman** [comment]
It's fine to reinterpret, or even propose a change, but it would be better if we didnt do this now, at the tail end of releasing the app. The staff here are the ones entering the data and they have been trained to understand license and access as such.  If a work has an access restriction, it can be fairUse, for copyright works, or if there are additional restrictions beyond fairUse, those are applied as appropriate, So any proposal would require a change in the schema, a change in the UI and a normalization of the existing data.  I think we should stick with the existing license and access policies until we are farther along in BUDA and then make the change in the migration as needed, at that time.

**Comment by subsystem7** [comment]
Speaking exclusively about PDF Generation errors, 
 - I call the PdfServiceApp
 - the response has key named "success"  
 - if success is "false" I look at the "errorCode" and present the corresponding error. The code is very simple, just a big if/else

```
// Type 2
				if('noAccessRight'===json.errorCode) {
					this.errorMessage = this.props.strings.noAccessRight + this.props.strings.type2PDFErrorMessage;
				} else if('noneSealedRight'===json.errorCode) {
					this.errorMessage = this.props.strings.noneSealedRight + this.props.strings.type2PDFErrorMessage;
				} else if('noneTemporaryRight'===json.errorCode) {
					this.errorMessage = this.props.strings.noneTemporaryRight + this.props.strings.type2PDFErrorMessage;
				} else if('noneQualityRight'===json.errorCode) {
					this.errorMessage = this.props.strings.noneQualityRight + this.props.strings.type2PDFErrorMessage;
				} else if('noneTbrcRight'===json.errorCode) {
					this.errorMessage = this.props.strings.noneTbrcRight + this.props.strings.type2PDFErrorMessage;
				} else if('noneChinaRight'===json.errorCode) {
					this.errorMessage = this.props.strings.noneChinaRight + this.props.strings.type2PDFErrorMessage;
				} else if('fairUseRight'===json.errorCode) {
					this.errorMessage = this.props.strings.fairUseRight + this.props.strings.type2PDFErrorMessage;
				} 

				// Type 3
				else if('noneByCopyright'===json.errorCode) {
					this.errorMessage = this.props.strings.noneByCopyright + this.props.strings.type3PDFErrorMessage;
				} 

				// Type 1
				else if('ExceptionRaised'===json.errorCode) {
					this.errorMessage = this.props.strings.ExceptionRaised + this.props.strings.type1PDFErrorMessage;
				} else if('ProcessTimeout'===json.errorCode) {
					this.errorMessage = this.props.strings.ProcessTimeout + this.props.strings.type1PDFErrorMessage;
				} else if('noImages'===json.errorCode) {
					this.errorMessage = this.props.strings.noImages + this.props.strings.type1PDFErrorMessage;
				} else if('pdfFailed'===json.errorCode) {
					this.errorMessage = this.props.strings.pdfFailed + this.props.strings.type1PDFErrorMessage;
				} else if('exceptionOccurred'===json.errorCode) {
					this.errorMessage = this.props.strings.exceptionOccurred + this.props.strings.type1PDFErrorMessage;
				} else if('unknownError'===json.errorCode) {
					this.errorMessage = this.props.strings.unknownError + this.props.strings.type1PDFErrorMessage;
				} else if('notInArchive'===json.errorCode) {
					this.errorMessage = this.props.strings.notInArchive + this.props.strings.type1PDFErrorMessage;
				} else if('noWorkDirectory'===json.errorCode) {
					this.errorMessage = this.props.strings.noWorkDirectory + this.props.strings.type1PDFErrorMessage;
				} else if('sampleAccessRight'===json.errorCode) {
					this.errorMessage = this.props.strings.sampleAccessRight + this.props.strings.type1PDFErrorMessage;
				} else if('openAccessRight'===json.errorCode) {
					this.errorMessage = this.props.strings.openAccessRight + this.props.strings.type1PDFErrorMessage;
				} else if('allAccessRight'===json.errorCode) {
					this.errorMessage = this.props.strings.allAccessRight + this.props.strings.type1PDFErrorMessage;
				} else if('ctcAccessRight'===json.errorCode) {
					this.errorMessage = this.props.strings.ctcAccessRight + this.props.strings.type1PDFErrorMessage;
				} else if('openAccessRight'===json.errorCode) {
					this.errorMessage = this.props.strings.openAccessRight + this.props.strings.type1PDFErrorMessage;
				}
```

There are three categories of error, as you can see from the code above. Error numbers are displayed, followed by one of three generic errors.  Both the codes and the generic errors are configurable through the localization settings.

**Comment by eroux** [comment]
I agree it's more simple if the dataset for the app reflects the current features instead  of more experimental ones, I'll make a new dataset, possibly tonight.

**Comment by eroux** [comment]
New dataset has been produced and sent to Asa
