### ISSUE TITLE
"sub" collection links broken

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/BDRC-Lib-App#68]
When set up on the international mirror and browsing to a collection, the link to the library is broken, NT's example is:

https://library.bdrc.io/scripts/embed-iframe.html?work=bdr:undefined&origin=BDRCLibApp1.2.0&lang=bo-x-ewts&uilang=en

note the `bdr:undefined`

**Comment by eroux** [comment]
@ngawangtrinley can you describe it better? which steps did you make to produce the bug?

**Comment by ngawangtrinley** [comment]
![](https://lh4.googleusercontent.com/S2S7p3Y4dpliavgCzx4FouamhfzucAt3_LE3EyG_QAavmAAjLVHED3Wy7iXyd0cEwakZkA8BB49dhVEvQxKvuALDGWUiq2_7DIdhHsQGhyy6TyfFxWKkEhxhBlPH4cJ32ScVQpMQMFg)

**Comment by eroux** [comment]
https://library.bdrc.io/scripts/embed-iframe.html?work=bdr:MW22084&origin=BDRCLibApp1.2.0&lang=bo-x-ewts&uilang=en

and

https://library.bdrc.io/scripts/embed-iframe.html?work=bdr:W22084&origin=BDRCLibApp1.2.0&lang=bo-x-ewts&uilang=en

are equally valid (so the ID can start with W or MW)

**Comment by subsystem7** [comment]
The app produces this link:
https://library.bdrc.io/scripts/embed-iframe.html?work=bdr:MW22084&origin=BDRCLibApp1.2.0&lang=bo-x-ewts&uilang=en

I get to this link by:

1. search for MW22084
2. select the only result
3. click on the "web" link at the bottom

However, the resulting page is blank.

**Comment by subsystem7** [comment]
reproduce by searching for a sub-collection: MW29701_4BEF40

**Comment by ngawangtrinley** [comment]
solved
