### ISSUE TITLE
missing shad (།) in the interface

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/BDRC-Lib-App#70]
Here's the screenshot from NT:

![pasted image 0](https://user-images.githubusercontent.com/60868/116700024-96968e00-a9c6-11eb-9821-d2011d5b811c.png)

the problem is that the title is missing a shad (`།`) at the end of the title in the yellow background, it should be `...བདེ་ལེགས་ཞུ།` instead of just `...བདེ་ལེགས་ཞུ`. The shad is in the data, the title is in `workparts/MW29701.json`:

```json
{"id": "MW29701_4BEF40", "t": ["བོད་ལྗོངས་བོད་ལུགས་གསོ་རིག་སློབ་གྲྭ་ཆེན་མོ་བཙུགས་ནས་ལོ་ངོ་བཅུ་འཁོར་བར་བཀྲ་ཤིས་བདེ་ལེགས་ཞུ།"]}
```

**Comment by ngawangtrinley** [comment]
The same is true for all other titles... Does it mean the data in the latest app is still the old data?

![](https://user-images.githubusercontent.com/17675331/116955697-d959ae00-acc5-11eb-9a23-4db400d57737.png)

**Comment by eroux** [comment]
@subsystem7 what do you think? (my understanding is that the data is correct, that must be a glitch in the interface)

**Comment by subsystem7** [comment]
@eroux This is indeed a data problem in the index file. In workparts-1.json it is listed like this, with no shad:

```"བོད་ལྗོངས་བོད་ལུགས་གསོ་རིག་སློབ་གྲྭ་ཆེན་མོ་བཙུགས་ནས་ལོ་ངོ་བཅུ་འཁོར་བར་བཀྲ་ཤིས་བདེ་ལེགས་ཞུ":["MW29701_4BEF40"]```

in workparts/cc.json I see the shad, but the title is created from the index for reasons of consistency:

 {"t": ["བོད་ལྗོངས་བོད་ལུགས་གསོ་རིག་སློབ་གྲྭ་ཆེན་མོ་བཙུགས་ནས་ལོ་ངོ་བཅུ་འཁོར་བར་བཀྲ་ཤིས་བདེ་ལེགས་ཞུ།"], "id": "MW29701_4BEF40"}

**Comment by eroux** [comment]
should be fixed in the latest data, I've updated https://staticfiles.bdrc.io/BDRCLibApp/1.2/current.json and https://staticfiles.bdrc.io/BDRCLibApp/1.2/BDRCLIB.zip
