### ISSUE TITLE
Localization: དྲ་ཚིགས། to དྲ་ཐག

### ISSUE THREAD

**Issue by tadhondup** [BuddhistDigitalResourceCenter/BDRC-Lib-App#74]
In English (WEB LINK) Need to replace དྲ་ཚིགས། to དྲ་ཐག in Tibetan

![180693783_797215394561890_8890483515494818020_n](https://user-images.githubusercontent.com/28945342/116954761-6cddaf80-acc3-11eb-9124-431a774fed4e.jpg)

**Comment by subsystem7** [comment]
changed in localization file
