### ISSUE TITLE
Reduce space between images

### ISSUE THREAD

**Issue by tadhondup** [BuddhistDigitalResourceCenter/BDRC-Lib-App#76]
The gap between images takes up a lot of screen space. Should be reduce to match mobile screens.

![180805747_533925024440329_6834694362255700275_n](https://user-images.githubusercontent.com/28945342/116955698-da8adb00-acc5-11eb-8324-fa2a2b141533.jpg)

![180816111_1663676703828060_1190319471307265633_n](https://user-images.githubusercontent.com/28945342/116955988-b54a9c80-acc6-11eb-9db7-a2ba07d47ccb.jpg)

**Comment by eroux** [comment]
thanks! moved to https://github.com/buda-base/public-digital-library/issues/471
