### ISSUE TITLE
Navigation inside the IIIF reader

### ISSUE THREAD

**Issue by ngawangtrinley** [BuddhistDigitalResourceCenter/BDRC-Lib-App#78]
Parent outline (in grey) not clickable/accessible from within the viewer, is it on purpose? 

![](https://user-images.githubusercontent.com/17675331/116955947-8cc2a280-acc6-11eb-929d-d05ed17478a4.png)

**Comment by eroux** [comment]
I think so yes... are there use cases where accessing the parent would be good?

**Comment by eroux** [comment]
oh sorry I misunderstood the issue, forget about my question

**Comment by eroux** [comment]
moved to https://github.com/buda-base/public-digital-library/issues/472, don't hesitate to comment there
