### ISSUE TITLE
Data: append alternative title when titles are duplicated

### ISSUE THREAD

**Issue by ngawangtrinley** [BuddhistDigitalResourceCenter/BDRC-Lib-App#79]
Welcome to the Tibetan edition of _Where is Waldo?_

![](https://user-images.githubusercontent.com/17675331/116956155-1d00e780-acc7-11eb-8ba7-cbda12165e09.png)

Duplicate titles have a unique alternative title, these should be added to the search results:

![](https://user-images.githubusercontent.com/17675331/116956254-63eedd00-acc7-11eb-9688-2e46d7f62fdf.png)

**Comment by eroux** [comment]
this is in the data, not the app, I'll create a tag for these, no action needed from @subsystem7

**Comment by eroux** [comment]
should be fixed in the latest data
