### ISSUE TITLE
Tibetan Typos

### ISSUE THREAD

**Issue by subsystem7** [BuddhistDigitalResourceCenter/BDRC-Lib-App#8]
There are some typos: སྙེ་ཆས། need to be corrected to མཉེན་ཆས།

Tibetan word ཡིག་འབྲུ་གཉིས་ means letter and here need syllable instead of letter, therefore, correct word will be either of ཚེག་ཁྱིམ་གཉིས་ ཚེག་བར་གཉིས་

**Comment by ngawangtrinley** [comment]
Done. The [localization spreadsheet](https://docs.google.com/spreadsheets/d/1lIlpgeRqdVaOoL7Rf4m7aikhsQwmrtRX-iAS39Y3eyY/edit#gid=0) has been revised by librarians.

**Comment by subsystem7** [comment]
Thank you, NT!! Can you indicate with red where in the spreadsheet you made these updates? It would help me find the changes a heck of a lot faster!!

**Comment by subsystem7** [comment]
Updates made.
