### ISSUE TITLE
Reduce font size of page numbers

### ISSUE THREAD

**Issue by tadhondup** [BuddhistDigitalResourceCenter/BDRC-Lib-App#80]
The font of this litter is little large here. Reduce a little will be nicer.

![180736391_3958538910907044_3899134209745968809_n](https://user-images.githubusercontent.com/28945342/116956356-b16b4a00-acc7-11eb-9f8d-0213ee16f4cd.jpg)

![179573603_216039066623423_630307213065187246_n](https://user-images.githubusercontent.com/28945342/116956663-630a7b00-acc8-11eb-88d1-bad9fc0bf328.jpg)

**Comment by eroux** [comment]
moved to https://github.com/buda-base/public-digital-library/issues/471
