### ISSUE TITLE
Localization: update location selection text

### ISSUE THREAD

**Issue by tadhondup** [BuddhistDigitalResourceCenter/BDRC-Lib-App#82]
Following text should be updated with: "རྒྱལ་ཁབ་ཅིག་འདེམ།་་་་"

རྒྱལ་ཁབ་ཅིག་འདེམ།
རྒྱ་ནག་ནང་བཀོལ་སྤྱོད་བྱེད་ན་རྒྱ་ནག་ཟེར་བ་དེ་འདེམ། གཞུག་ནས་ཀྱང་འདི་སྒྲིག་འགོད་ནང་འགྱུར་བ་གཏོང་ཐུབ།

![180961177_463413904767810_2900090238764967355_n](https://user-images.githubusercontent.com/28945342/116958140-2e002780-accc-11eb-9a31-a7864de1ef39.jpg)

Please select your location
Select China as your location to view images and download PDFs in China. You can always change this later in settings.

![182045352_131723788974861_2939877204162426151_n](https://user-images.githubusercontent.com/28945342/116958144-348e9f00-accc-11eb-825a-1de1fb094b24.png)

**Comment by subsystem7** [comment]
@tadhondup Is this accurate (please note the removal of "PDF" which was in the original localization:

	pleaseSelectLocation:'རྒྱལ་ཁབ་ཅིག་འདེམ།',
	pleaseSelectLocationDescription:'རྒྱ་ནག་ནང་བཀོལ་སྤྱོད་བྱེད་ན་རྒྱ་ནག་ཟེར་བ་དེ་འདེམ། གཞུག་ནས་ཀྱང་འདི་སྒྲིག་འགོད་ནང་འགྱུར་བ་གཏོང་ཐུབ།',

Thanks,

Asa
