### ISSUE TITLE
Print Type Value Substitution

### ISSUE THREAD

**Issue by subsystem7** [BuddhistDigitalResourceCenter/BDRC-Lib-App#85]
This is a reference to one question in #81 

"Parts of collections are replaced by an x ... Or is it something else? "

![116957068-7e29ba80-acc9-11eb-841d-4e0cd2d22282](https://user-images.githubusercontent.com/1638461/117659742-4f4c9200-b16a-11eb-87c9-7482ab98376f.png)

**Comment by subsystem7** [comment]
inside of works/03.json:
`"MW26071": {"pt": "x", "hasParts": true, "pl": "ལྷ་ས།", "pn": "ཞོལ་བཀའ་འགྱུར་པར་ཁང་།", "title": ["བཀའ་འགྱུར ༼ལྷ་ས༽"], "pd": "0194-"}`

The Print Type (aka, pt) has a value of "x"

**Comment by subsystem7** [comment]
@ngawangtrinley & @eroux  This is data, not app.

**Comment by eroux** [comment]
Ah, actually this is a feature of the data to keep a bit of space, the values are:
- `x` = `Woodblock` / `ཤིང་པར།` / `雕版`
- `m` = `Manuscript` / `བྲིས་མ།` / `写本`
- `mo` = `Modern print` / `??` / `??` (@ngawangtrinley could you help with that? maybe `རྩིས་འཁོར་ནང་དུ་འཇུག་པ།` / `电脑输入`)
- `l` = `Xerography` / `པར་སློག` / `静电复印`

@subsystem7 can we make the app substitute these values?
