### ISSUE TITLE
number of results in search depends on UI language

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/BDRC-Lib-App#86]
From the librarians, steps to reproduce:
- set the language to "English"
- search "དེབ་ཐེར་དཀར་" 
- get 6 results (correct)

![1 Search_Result_English](https://user-images.githubusercontent.com/60868/118523194-32512980-b73d-11eb-81d8-12a6e6165cfd.PNG)

- set the language to Tibetan
- search "དེབ་ཐེར་དཀར་" 
- get 16 results (`བཙལ་འབྲས་ ༡༦`, incorect)

![2 Search_Result_Tibetan](https://user-images.githubusercontent.com/60868/118523230-3b41fb00-b73d-11eb-9114-092ea13cc4a9.jpg)

Perhaps there's just a spurious `༡` in the translation string?

**Comment by subsystem7** [comment]
Please check this table generated by the num conversion function that is now in place

[test_tib_nums.pdf](https://github.com/buda-base/BDRC-Lib-App/files/6495951/test_tib_nums.pdf)

**Comment by eroux** [comment]
looks good, thanks!
