### ISSUE TITLE
allowing scan RID to be used in the search

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/BDRC-Lib-App#88]
Since it's possible to search by RID and since many people are more used to the `W` RIDs than the `MW` ones, let's allow users to search by scan RID by hacking a little adjustment:
- if a user searched a string that starts with `W`, search `M`+the string, for instance if a user searches `W22084`, the app should return results for `MW22084` instead

**Comment by subsystem7** [comment]
I may look into adding the "M" in the search field while the user types. This would serve to train new behaviour, and not require a search / caching hack, where I maintain multiple realities.

**Comment by eroux** [comment]
ah good idea!
