### ISSUE TITLE
Publication Information is needed

### ISSUE THREAD

**Issue by subsystem7** [BuddhistDigitalResourceCenter/BDRC-Lib-App#9]
NT: It’s crucial for identification, title and authorship aren’t enough in many cases.
Karma: Need full publication information show.

**Comment by eroux** [comment]
@ngawangtrinley we currently transfer `pubinfo_printType`, `pubinfo_publisherDate` and `pubinfo_publisherLocation` to the database (full list of transferred fields [here](https://github.com/BuddhistDigitalResourceCenter/bfa-data-transfer/blob/master/src/main/java/io/bdrc/bfadatatransfer/MigrationApp.java#L90)). Can you please provide a specific example of something that is needed but absent from the current data?

**Comment by ngawangtrinley** [comment]
This is the minimal information needed from the publication information, the information you currently transfer doesn't appear in the interface. 

* pubinfo_publisherName
* pubinfo_publisherDate
* pubinfo_publisherLocation
* pubinfo_publisherType
* (Series?)

![image](https://user-images.githubusercontent.com/17675331/27337409-f0ffe27a-5604-11e7-8b09-e309341de58b.png)

**Comment by eroux** [comment]
I'll build a new data set adding `publisherName`

**Comment by ngawangtrinley** [comment]
https://www.tbrc.org/#!rid=O8LS6083%7CO8LS60834CZ163395$W1PD107937

**Comment by subsystem7** [comment]
@ngawangtrinley I need the Tibetan for "Publisher Name"

**Comment by ngawangtrinley** [comment]
Updated in the spreadsheet.

Publisher Name - པར་མཁན།
Publisher Location - པར་གནས།
Publisher Date - པར་དུས།

**Comment by subsystem7** [comment]
@ngawangtrinley  Thank you! I also need "Print Type" and "RID"

**Comment by subsystem7** [comment]
![image](https://user-images.githubusercontent.com/1638461/27398399-a1247972-5687-11e7-8040-573f55aa3ae6.png)

**Comment by subsystem7** [comment]
![image](https://user-images.githubusercontent.com/1638461/27398446-c5812fd6-5687-11e7-9c3f-657fb3f7ba49.png)

**Comment by ngawangtrinley** [comment]
Could you do this order? Although it doesn't matter that much. Status can come last or not at all, it's not very useful for this release.
![image](https://user-images.githubusercontent.com/17675331/27400708-84484268-56f3-11e7-8da9-a1ab189763e0.png)

**Comment by subsystem7** [comment]
Yes! I modified the order to follow this example!

**Comment by jeffwallman** [comment]
I hope we still have the status variable present.  It is important to show people the state of a resource.  We are going to put in the acquisitions list in there so there will be more works listed as "seekingOut"
