### ISSUE TITLE
Add "clear" search button, standard material design "X"

### ISSUE THREAD

**Issue by JannTibetan** [BuddhistDigitalResourceCenter/BDRC-Lib-App#90]
At present the only way to start a new search is by manually deleting the previous search string. Can the BDRC Lib header function as a "new search" button?
![image](https://user-images.githubusercontent.com/44705185/118707878-0e4b2200-b7e9-11eb-97d3-cd79926edcc7.jpeg)

**Comment by subsystem7** [comment]
@JannTibetan the standard approach is an "x" in the search box to clear the value out.  We originally excluded this since it does not translate in meaning in Tibetan and Chinese. Maybe a "clear" button in all three languages could fit?

**Comment by JannTibetan** [comment]
@subsystem7 A "clear" button is a great solution (more self-explanatory than turning the app name into a button).

**Comment by subsystem7** [comment]
@ngawangtrinley need "clear" for Tib and Chinese - or equivalent. If users would understand an "x" in the search box as a clear tap target, then I can add that. Please advise.

**Comment by ngawangtrinley** [comment]
![](https://user-images.githubusercontent.com/17675331/119517785-7fbb3f80-bdaa-11eb-9075-1e9164fa3291.png)
