### ISSUE TITLE
Inconsistent results on person names

### ISSUE THREAD

**Issue by JannTibetan** [BuddhistDigitalResourceCenter/BDRC-Lib-App#91]
I wanted to find the person record for ཨ་ཏི་ཤ་ P3379
The search on ཨ་ཏི་ཤ་ did not yield the desired record even though this name does appear in his person record. 
![image](https://user-images.githubusercontent.com/44705185/118709212-b2819880-b7ea-11eb-9c60-5332c4a131d8.jpeg)
However searching on another of his names does yield the correct record. 
![image](https://user-images.githubusercontent.com/44705185/118709226-b6151f80-b7ea-11eb-85db-fe9846abe5d4.jpeg)

**Comment by subsystem7** [comment]
@JannTibetan @ngawangtrinley I may need some help navigating the data on this to see where and how the match is being made.  @eroux does this look like a data issue?

**Comment by JannTibetan** [comment]
@subsystem7 the two search strings are ཨ་ཏི་ཤ་ and མར་མེད་མཛད་ They are variants names of [P3379](http://purl.bdrc.io/resource/P3379)

**Comment by eroux** [comment]
@subsystem7 this looks like a bug in the search, as `persons-0.json` contains

```
"ཨ་ཏི་ཤ":["P3379"]
```

so there should be a match (ignoring the punctuation according to https://github.com/buda-base/BDRC-Lib-App/issues/71 )

**Comment by eroux** [comment]
sorry, I didn't take the right data, this is a data problem, I'll create a new release tomorrow

**Comment by eroux** [comment]
I've updated the data, perhaps this would be an opportunity to test the data update system?
