### ISSUE TITLE
Web Link options

### ISSUE THREAD

**Issue by JannTibetan** [BuddhistDigitalResourceCenter/BDRC-Lib-App#93]
"Open in Safari" would be nice to have as an option. As it works now this function is for sending/posting the web link, not for opening web page for the given record. ![image](https://user-images.githubusercontent.com/44705185/118712053-4f920080-b7ee-11eb-91aa-4df8071b6194.jpeg)

**Comment by subsystem7** [comment]
@JannTibetan I will look into this.

**Comment by ngawangtrinley** [comment]
That's an interesting one. We actually edited the Tibetan to "share web link", after assuming that the default viewer was the app itself. @subsystem7 what is the original intention of that feature: to open the IIIF reader in a browser or to share it? Either way is fine, we'll update the Tibetan accordingly

**Comment by subsystem7** [comment]
@ngawangtrinley I don't remember the original intention. It has become a copy/paste function. It was originally called "Share" as it was set up to take advantage of social sharing platforms (facebook, or whatever was set up on your phone etc...). I am not even sure if I can add the web browser to this button. I may need to look into a different plugin.  We should discuss the specific desires/needs here before I start look ing for solutions.

**Comment by ngawangtrinley** [comment]
View in app viewer:

![](https://user-images.githubusercontent.com/17675331/119513111-834cc780-bda6-11eb-8427-47b69a3398dc.png)

View in browser openned with link:

![](https://user-images.githubusercontent.com/17675331/119513616-f5251100-bda6-11eb-9705-648567701329.png)

**Comment by subsystem7** [comment]
@JannTibetan we determined that this link should simply be changed to "Share" - right?

**Comment by JannTibetan** [comment]
Hi @subsystem7 please make it "Share". I think that's a good function to have. I suggested the open in browser just as a "nice to have" but agree with NT that the app's viewer is sufficient. Thanks

**Comment by subsystem7** [comment]
@ngawangtrinley and @eroux would you make sure that the Strings file has three versions of "Share"?

**Comment by ngawangtrinley** [comment]
བརྒྱུད་སྐུར། in Tibetan
