### ISSUE TITLE
Description for launch

### ISSUE THREAD

**Issue by subsystem7** [BuddhistDigitalResourceCenter/BDRC-Lib-App#97]
Buddhist Digital Resource Center applies the transformative power of technology to advance the preservation and accessibility of Buddhist literature. BDRC Lib provides mobile access to the complete BDRC Library operating at tbrc.org.

BDRC Lib works offline to search thousands of titles in the library. Included are titles of independently published works, as well as titles that have been included in collections (via the outline feature of the BDRC Library). The app’s search tool works offline and online. Once the app is online, connected to the internet or a mobile data platform, readers can browse scanned page images, share texts, and download PDFs. 

BDRC is planning additional features, so please stay tuned for updates. Future releases will include collaborative features that give users the ability to request that a text be scanned, suggest edits to records, and suggest a text for inclusion in the library. BDRC will also release a desktop version of the mobile app that provides direct access to the BDRC Library on a computer.

**Comment by eroux** [comment]
Here's an attempt:

> Buddhist Digital Resource Center applies the transformative power of technology to advance the preservation and accessibility of Buddhist literature. BDRC Mobile provides mobile access to the Open Access Tibetan part of the BDRC library, otherwise available on our website.
> The app’s search tool can work offline, but the image viewer requires an Internet connection.

(I guess we shouldn't put a link to our website if we want the description to be PRC-friendly?)

I have to admit this new description isn't sexy at all...
