### ISSUE TITLE
make buttons' buttonness more clear

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/BDRC-Lib-App#99]
In views like this:

![1655125542155](https://user-images.githubusercontent.com/60868/173365548-a65e18f7-481b-4dcf-bb54-d84caedfe1d1.JPEG)

the two buttons at the bottom don't really look like buttons, a little but of css and / or icons would help users understand these are clickable

**Comment by subsystem7** [comment]
![Image](https://user-images.githubusercontent.com/1638461/179233499-3b43f6b0-4d83-499c-8874-3dc73365c008.png)



![Image](https://user-images.githubusercontent.com/1638461/179233670-b0e7953e-bea0-455b-a160-c11ecdc7979f.png)



![Image](https://user-images.githubusercontent.com/1638461/179233720-74b5c1e7-2161-4aae-8e89-31c39bcda368.png)

**Comment by eroux** [comment]
well, that's clearer for sure!
